// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBual8aez-p1L6JAXGxBRXvy_IngSb6Ovc',
    appId: '1:1064540716429:web:3af773910b14771f62d1c4',
    messagingSenderId: '1064540716429',
    projectId: 'habat-khardal-a9a1f',
    authDomain: 'habat-khardal-a9a1f.firebaseapp.com',
    storageBucket: 'habat-khardal-a9a1f.appspot.com',
    measurementId: 'G-JQENRCQ5V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMPjmzIhP3T-Qefk6oWFHdXVSA0CUXXB4',
    appId: '1:1064540716429:android:75fb20bc69fa0e5962d1c4',
    messagingSenderId: '1064540716429',
    projectId: 'habat-khardal-a9a1f',
    storageBucket: 'habat-khardal-a9a1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWth841Q2IC3PGXpTRYwbmLUYjfhsBWXQ',
    appId: '1:1064540716429:ios:97bc6eac4c29894f62d1c4',
    messagingSenderId: '1064540716429',
    projectId: 'habat-khardal-a9a1f',
    storageBucket: 'habat-khardal-a9a1f.appspot.com',
    iosBundleId: 'com.example.habatKhardal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWth841Q2IC3PGXpTRYwbmLUYjfhsBWXQ',
    appId: '1:1064540716429:ios:97bc6eac4c29894f62d1c4',
    messagingSenderId: '1064540716429',
    projectId: 'habat-khardal-a9a1f',
    storageBucket: 'habat-khardal-a9a1f.appspot.com',
    iosBundleId: 'com.example.habatKhardal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBual8aez-p1L6JAXGxBRXvy_IngSb6Ovc',
    appId: '1:1064540716429:web:ac019b885bad654a62d1c4',
    messagingSenderId: '1064540716429',
    projectId: 'habat-khardal-a9a1f',
    authDomain: 'habat-khardal-a9a1f.firebaseapp.com',
    storageBucket: 'habat-khardal-a9a1f.appspot.com',
    measurementId: 'G-M80FRHWT7D',
  );
}
